[entry]
dir = "./src"
infile = "main.cpp"

[output]
dir = "./dist"
outfile = "[name].js"
# To serve the outfile, comment out the below line.
# If unspecified, serve the outfile.
served = "index.html"

[build]
params = [""]
watch = true